apiVersion: v1
kind: Service
metadata:
  name: amonkincloud-cluster
spec:
  selector:
    app: amonkincloud-cluster  # Match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80       # Port on which the service will be exposed externally
      targetPort: 80  # Port on which Flask application is running inside the container
  type: LoadBalancer
